### PR TITLE
Allowed loading files with acquisition ratio >1

### PR DESCRIPTION
**Pull request by peq10**
This project failed if the acquisition ratio (electrical signal data rate/camera frame rate) was greater than 1. I added the capability to deal with this. 

I also changed the loading from memmap to  fromfile. This is because memmap failed to load the correct data with my set up - I am unsure why. I don't think that this is a disadvantage as the all of the data is loaded into memory anyway.

### CODE REVIEW

**Comment by jni** [comment]
Hey @peq10, thanks for this enhancement!

As you can probably tell, this library was not developed very far past its original use. Since it has now reached the >1 user threshold, I'd like to have a couple of tests. Would you be able to provide a test volume? If you can provide a link to a test file, I'd be happy to write some tests for it.

Thanks!

**Comment by peq10** [comment]
Hi @jni,

I'm fairly new to all of this and not very familiar with the testing process. I am happy to organise a test volume although don't know how - could you point me towards a tutorial if it isn't too much bother?

Cheers

**Comment by jni** [comment]
@peq10 

Well you've made a pull request so you already know how to do the hardest part! =)

The idea is to add a folder, `tests/` at the top level of this repository (next to `redshirt/`). In that directory, you can add an example data file (preferably a small one), and write a module, `test_io.py`, with a function, `def test_read():`, that reads your volume and then uses one or more `assert` statements to check that the volume is read correctly (the image is of the right shape, has the right dtype, the values are in the order you expect, etc.).

I wrote a small guide on this here:

https://ilovesymposia.com/2014/10/01/continuous-integration-0-automated-tests-with-pytest/

Let me know if you need further clarifications, and thank you!

**Comment by jni** [comment]
@peq10 did you get a chance to try your hand at this? Happy to help further if you need! btw, where are you based?

**Comment by peq10** [comment]
Hi @jni sorry for the delay - I have been wrapped up in writing a paper and got distracted! I am keen to try my hand at setting this up I just have been slow as I have been using someone else's unpublished redshirt imaging data and didn't have a suitable test file. Do you happen to have a small file we could use?

I am a PhD student based in London - I use Python and scipy a lot in my work and wanted to try contributing to a small repository!

**Comment by jni** [comment]
@peq10 Cool! We'll have you contributing to SciPy et al in no time. =)

I can probably get some redshirt files but they will have whatever acquisition ratio worked with this before your PR, so they won't be a good test for this. Maybe you can either:
- contact your collaborator to provide a single file (maybe a control or something, not like anyone is going to scoop them based on a single, unannotated acquisition!)
- contact your collaborator to take a dummy measurement so we can get such a file
- wait for publication.

Any of these is fine my me. =)

**Pull request merged**
